FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS 'mysqlUser'@'%' IDENTIFIED BY 'mysqlUserPass';

CREATE DATABASE IF NOT EXISTS mysqlDb;

GRANT ALL PRIVILEGES ON mysqlDb.* TO 'mysqlUser'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'mysqlRootPass';
